on:
  push:
    branches:
      - main
name: Build Jorna
jobs:
    build_app:
        runs-on: macos-15
        name: Build Jorna
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install the Apple certificate and provisioning profile
          env:
            MAC_DEV_CER: ${{ secrets.MAC_DEV_CER }}
            P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
            DEVELOPER_ID_CER_PATH: ${{ secrets.DEVELOPER_ID_CER_PATH }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          run: |
              MAC_DEV_CER_PATH=$RUNNER_TEMP/madev.p12
              DEVELOPER_ID_CER_PATH=$RUNNER_TEMP/devid.p12
              KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
              echo -n "$MAC_DEV_CER" | base64 --decode -o $MAC_DEV_CER_PATH
              echo -n "$DEVELOPER_ID_CER" | base64 --decode -o $DEVELOPER_ID_CER_PATH
              security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
              security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
              security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
              security import $MAC_DEV_CER_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
              security import $DEVELOPER_ID_CER_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
              security list-keychain -d user -s $KEYCHAIN_PATH
        - name: Build Jorna.app
          run: |
            mkdir -p dist
                xcodebuild \
                    archive \
                    -project Jorna.xcodeproj/ \
                    -scheme Jorna \
                    -destination 'generic/platform=macOS' \
                    -archivePath dist/Jorna.xcarchive
                npx create-dmg dist/Jorna.xcarchive/Products/Applications/Jorna.app dist/
                mv dist/Jorna*.dmg dist/Jorna.dmg
        - name: Notarize App
          env:
            NOTARY_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
            NOTARY_APPLE_ID: ${{ secrets.NOTARIZATION_USERNAME }}
          run: |
            xcrun notarytool submit \
            --team-id 'K64KJB8N6L' \
            --apple-id "$NOTARY_APPLE_ID" \
            --password "$NOTARY_PASSWORD" \
            --wait \
            dist/Jorna.dmg
            xcrun stapler staple dist/Jorna.dmg
        - name: Upload Jorna.dmg
          uses: actions/upload-artifact@v4
          with:
            name: Jorna.dmg
            path: dist/Jorna.dmg